name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [adder, closure]
    
    steps:
      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request'
      - name: Build
        run: |
          cd LearnRust/${{ matrix.project }}
          echo $(ls)
          cargo build --verbose
      - name: Run tests
        run: |
          cd LearnRust/${{ matrix.project }}
          echo $(pwd)
          cargo test --verbose
