name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [traits, guessing_game]
        
    steps:
      - uses: actions/checkout@v4
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build
        run: |
          cd ${{ matrix.project }}
          cargo build --verbose
      - name: Run tests
        run: |
          cd ${{ matrix.project }}
          cargo test --verbose
