name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [adder, closure]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build
        run: |
          cd LearnRust
          echo $(ls)
      - name: Run tests
        run: |
          cd LearnRust
          echo $(pwd)
